### ISSUE TITLE
tool

### ISSUE THREAD

**Issue by asuivelentine** [matthiasbeyer/hfu-thesis.pandoc#7]
du hattest noch n weiteres tool welches in die vorlage eingebunden werden soll. welches war das? machst du dafuer noch n issue?

**Comment by asuivelentine** [comment]
blockdiag/msc und R sind nicht im setup enthalten. Denke graphviz, plantuml und svgbob decken die anwendungsfaelle ab.

**Comment by matthiasbeyer** [comment]
Naja falls R notwendig werden sollte kann man es relativ einfach dazubasteln. Ist halt geil für Graphen. Aber jo. Passt.
